# Async pipe 异步管道



诶think π婆，异步管道



## 用途



使用 async pipe 可以直接在模板中访问 observable



## subscribe



当 component 被初始化 （initialize）时，异步管道自动订阅 observable 对象，**并返回每一个 emit 的值**。



## detect changes



当模板里的 observable **有新的 item emit 时**，组件会 NG 标记为“有改变”，并运行变更检测。

### change detection 变更检测

NG 使用变更检测来标记 application data 的变化，以便更新 UI

可以选择变更检测的策略来增强 performance：

1. Default：总是检测所有 components 的所有 changes
2. OnPush：只在三种情况下检测，以提高性能
   1. input 属性改变
   2. 事件触发
   3. async pipe observe 的 observable emits 了 item

<img src="imgs\changeDetection.png" style="zoom:60%;" />



## unsubscribe



async pipe 在 component 销毁（destroy）时，自动取消订阅，避免潜在的内存泄漏。



# 处理 observable 的错误



## 用途



防止异步操作或事件的 Error 使我们的程序崩溃。

因为 observable 一旦出现错误，就不会再 emit 任何 items，并且不会调用 complete() 方法，意味着不能再使用它了



## 步骤



1. catch 错误，防止程序崩溃
2. 不处理，再次 throw 错误，沿着订阅链传递
3. 用新的 observable 替换有错误的 observable



## RxJS 提供处理 error 的 feature



1. catchError

2. throwError

3. EMPTY，空的 observable

   

catchError 捕获任何错误，防止沿订阅链传播，catchError 需要放在可能产生错误的操作之后

throwError 基本上是一个 creation function，throwError 创建一个新的用于替换的 observable，且不会 emit 任何 items，在被订阅时立即给订阅者发出错误通知。return throwError(()=> new Error('could not retrieve')) 将错误传播到应用程序的其他部分（组件）。

大多数情况下，可以简单的使用 JS throw 语法抛出一个错误：throw new Error('could not retrieve'))。

EMPTY 常量用于创建一个空的 observable，EMPTY 常量不会 emit 任何 items，在被订阅时立即发出 complete 通知。常用于 observable 发生错误又没有默认值可以替换时使用 EMPTY 常量



## RxJS catchError demo



此时 observer 的 error 方法 不会 observe 到错误，因为已经被 catch 住了

<img src="imgs\catchError.png" style="zoom:60%;" />

由于新的 observable 是由 of creation function 构建的，所以在 emit 完 six 后，会自动 complete()

<img src="imgs\catchErrorDiagram.png" style="zoom:60%;" />



```ts

import { of, map, Observable, catchError } from 'rxjs';

of(2, 4, 6, 8, 10)
  .pipe(
    map((x) => {
      if (x === 6) {
        throw 'error!!!';
      }
      return x;
    }),
    catchError((err) => of('six'))
  )
  .subscribe({
    next: (x) => console.log(x),
    error: (err) => console.error(err),
    complete: () => console.log('completed!'),
  });

// 输出：

2

4

six

completed!

```



## RxJS throwError demo



<img src="imgs\throwError.png" style="zoom:60%;" />

不管用 return throwError() 还是 throw new Error()，都把错误抛给了 component，因此在 component 中 需要 catchError

<img src="imgs\throwError2.png" style="zoom:60%;" />